# **Numpy**

# **Numpy**

# **if you face any probelm undersatnding please follow this link - https://chatgpt.com/c/f8eefefb-ddbd-4986-974a-09b78f8fc81c**

In [4]:
import numpy as np

In [ ]:
# two dimensional array
mylist = [[2 , 3 , 4] , [3 , 4 , 5]]
print(np.array(mylist))

[[2 3 4]
 [3 4 5]]


In [ ]:
# numpy array suing arrange and steps

mynewlist = np.arange(0 , 11 , 2)   #  first one (0) is start number  (11) how many number after 0 and last(2) steps its +2 after 0
print(mynewlist)

[ 0  2  4  6  8 10]


In [ ]:
# one and zeros for in np array
one = np.ones(4)
print(one)
two = np.ones((2,3))
print(two)
three = np.zeros(3)
print(three)
four = np.zeros((3 , 4))
print(four)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# linspace() creates an array of evenly spaced values over a specified interva
np.linspace(0 , 5 , 10)  # basically its create the gap number between 0 to 5 and gaps are 10 number with points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
# linspace() 2D array
np.linspace((0 , 3 , 3),(0 , 2 , 2))  # not a great way because here for 2d array its give 50 if you dont define num = what you want like that below

array([[0.        , 3.        , 3.        ],
       [0.        , 2.97959184, 2.97959184],
       [0.        , 2.95918367, 2.95918367],
       [0.        , 2.93877551, 2.93877551],
       [0.        , 2.91836735, 2.91836735],
       [0.        , 2.89795918, 2.89795918],
       [0.        , 2.87755102, 2.87755102],
       [0.        , 2.85714286, 2.85714286],
       [0.        , 2.83673469, 2.83673469],
       [0.        , 2.81632653, 2.81632653],
       [0.        , 2.79591837, 2.79591837],
       [0.        , 2.7755102 , 2.7755102 ],
       [0.        , 2.75510204, 2.75510204],
       [0.        , 2.73469388, 2.73469388],
       [0.        , 2.71428571, 2.71428571],
       [0.        , 2.69387755, 2.69387755],
       [0.        , 2.67346939, 2.67346939],
       [0.        , 2.65306122, 2.65306122],
       [0.        , 2.63265306, 2.63265306],
       [0.        , 2.6122449 , 2.6122449 ],
       [0.        , 2.59183673, 2.59183673],
       [0.        , 2.57142857, 2.57142857],
       [0.

In [ ]:
np.linspace((0 , 1),(2 , 3) , num = 5)
# Start: (0, 1) — This is the starting point of the linear interpolation.
# Stop: (2, 3) — This is the stopping point of the linear interpolation.

array([[0. , 1. ],
       [0.5, 1.5],
       [1. , 2. ],
       [1.5, 2.5],
       [2. , 3. ]])

In [ ]:
# its is use ful for linear algebra here all rows and coloum are 0 but only diagonal of 1
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# random samples from uniform distribution 0 to 1
np.random.rand(4) # its gives random number of 0 to 1 but between 0 to 1

array([0.45169696, 0.16790791, 0.33703036, 0.61229687])

In [ ]:
# same thing in 2D array no need to define in tuples
np.random.rand(4,4)

array([[0.87266292, 0.63867571, 0.6071678 , 0.46017207],
       [0.13447468, 0.17852268, 0.75689843, 0.52774607],
       [0.58186791, 0.76622493, 0.21701106, 0.80588067],
       [0.89667772, 0.02957363, 0.67870608, 0.36606118]])

In [ ]:
# Standard Normal Distribution Around 0:
# In simple terms: Most values in a standard normal distribution are close to 0,
# with fewer values as you move further away, creating a bell-shaped curve.
np.random.randn(4)

array([-0.21085326,  1.01093188, -0.65811686,  1.33896886])

In [ ]:
# random integer
np.random.randint(1 , 10 , 5)  # first low (inclusive) 2nd high (exclusive) last the number you want
# here its start from 1 but not include 10

array([9, 6, 3, 7, 8])

In [ ]:
# reshape methord but its show error if the number not fit from the real array
arr = np.arange(25)
# arr.reshape(5,3) its show error the the number is 25 but its only use 15
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# we can cheak any array max and min value and its index
ranarr = np.random.randint(1, 100, size=(3, 5))  # size: The shape of the output array.
print(ranarr)
# max and min value
max = ranarr.max()
print(f"max {max}")
min = ranarr.min()
print(f"min {min}")
# max and min value index
maxI = ranarr.argmax()
minI = ranarr.argmin()
print(f"min {maxI}")
print(f"min {minI}")

[[30 17 78 47 23]
 [51 90 57 58  0]
 [32 59  1 64 79]]
max 90
min 0
min 6
min 9


In [ ]:
ranarr.shape

(3, 5)

In [ ]:
# data typeof array
newarr = np.array([10,20,30])
ranarr.dtype  # for 2d arrays its also 64bit
newarr.dtype

dtype('int64')

# ***Numpy indexing and selection***

In [ ]:
larr = np.arange(1 , 11)
# grab the index value and slice the array
print(larr[8])
print(larr[0 : 5])
print(larr[4 : ]) # here its print 4 to all the way end here actually we pass the index not the value its grab the value after that index here

9
[1 2 3 4 5]
[ 5  6  7  8  9 10]


In [ ]:
randomarray = np.random.randint(0 , 11 , 10)
print(randomarray)
# in this randomarray i set the first 4 number is 7 by
randomarray[0 : 4] = 7
print(randomarray)
# dont get confused eveytime the number is changing

[10  3  6  2  1  6  6  7  9  9]
[7 7 7 7 1 6 6 7 9 9]


**Numpy dont set copies of array instant its change the array if you define the array variable name same for other array variable name**

In [18]:
arr = np.arange(0 , 11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [17]:
changeArray = arr[:]
changeArray[:] = 99
print(changeArray)
print(arr)
# here updated array and old arry two change

[99 99 99 99 99 99 99 99 99 99 99]
[99 99 99 99 99 99 99 99 99 99 99]


In [26]:
# if you want to change the value but not affect the old array then use copy
new_Arr = np.random.randint(0 , 20 , 10)
print(new_Arr)
new_Arr_copy = new_Arr.copy()
new_Arr_copy[:5] = np.arange(0 , 5)
print(new_Arr_copy)

[ 9  4  2  1  2  3  3  6 15  5]
[ 0  1  2  3  4  3  3  6 15  5]


In [30]:
# using single bracket comma notation
new_2D = np.random.randint(1 , 100 ,size=(3,3))
print(new_2D)

# here i want to grab the 2nd row 3rd item
print(new_2D[1 , 2])

[[24 93 89]
 [89 34 52]
 [53 39 35]]
52


In [36]:
# here i grab the 2nd and 3rd row 2nd and 3rd coloum
new_2D_array = np.random.randint(0 , 10 ,  size=(3 , 5))
print(new_2D_array)
# now grab
print(new_2D_array[1 : 3 , 1 : 3])

[[2 0 5 2 4]
 [9 2 0 5 5]
 [1 5 6 6 3]]
[[2 0]
 [5 6]]


In [62]:
full_Array = np.arange(1 , 51).reshape(5 ,10)
print(full_Array)
# grabbing 12 to 30 in array format
print("# grabbing 12 to 30 in array format")
print(full_Array[1 : 3 , 1 : ])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
# grabbing 12 to 30 in array format
[[12 13 14 15 16 17 18 19 20]
 [22 23 24 25 26 27 28 29 30]]


# **comparison operators python**

In [55]:
def fun():
  random_Newarray = np.random.randint(0 , 20 , size=[1 , 12])
  boolarray = random_Newarray > 5
  print(f"First array {random_Newarray}")
  print(f"2nd array True / false the number greater than 5 {boolarray}")
  print(f"finally the number itself that greater than 5 {random_Newarray[boolarray]}")

fun()

First array [[12  2 16  3 16  8 13 13  3  0  6 14]]
2nd array True / false the number greater than 5 [[ True False  True False  True  True  True  True False False  True  True]]
finally the number itself that greater than 5 [12 16 16  8 13 13  6 14]


[[19  1  1  6 12  7]]
[[ True False False  True  True  True]]
[19  6 12  7]
